### ISSUE TITLE
Make GPfit more object oriented(?)

### ISSUE THREAD

**Issue by pgkirsch** [convexengineering/gpfit#11]
It might be more elegant to make classes of fits, e.g. `ISMA_fit`, `SMA_fit`, `MA_fit`.

These classes could then have functions such as `plot_fit` (for 1D and 2D functions) and `print_fit` (which already exists).

**Comment by bqpd** [comment]
Kinda did this in the refactor, by just making them ConstraintSets and then giving them an `evaluate` method.
