### ISSUE TITLE
Issue with plot functionality (or tutorial documentation)

### ISSUE THREAD

**Issue by blakecole** [convexengineering/gpfit#111]
The GPFit Tutorial documentation specifies:

Once a fit is generated, we can plot it:

fig, ax = f.plot() # for 1D fits
fig, ax = f.plot_slices() # for 2D fits
fig, ax = f.plot_surface() # for 2D fits

When I append this code to Example 1, the program executes to completion (with no stated errors), but no figure appears.

**Comment by whoburg** [comment]
Hi @blakecole, have you tried running `fig.show()` to get the figure to appear? Might be an easy fix.

**Comment by blakecole** [comment]
I am mortified, but I believe this was indeed the issue.  Thanks!

**Comment by whoburg** [comment]
ha, no prob! glad that worked.
