### ISSUE TITLE
Identify why fitting process seems to time out for relatively "easy" problems

### ISSUE THREAD

**Issue by pgkirsch** [convexengineering/gpfit#12]
Relatively straightforward fitting problems seem to be cause GPfit to reach the max time limit (5 seconds). Examples of such problems are ex61.py and ex63.py, which are both taken from the GPfit paper.

The fact they are reaching max time can be found be re-enabling the `verbose` option

**Comment by pgkirsch** [comment]
Can't reproduce

**Comment by whoburg** [comment]
haha excellent resolution from the issue author 😄
