### ISSUE TITLE
duplicate examples directory

### ISSUE THREAD

**Issue by whoburg** [convexengineering/gpfit#28]
examples in `gpfit/examples/` should be updated / renamed as appropriate, moved to `docs/source/examples`, and added to `tests/t_examples`.

**Comment by pgkirsch** [comment]
It seems like the example 6-1 was duplicated in `docs/source/examples` around the time of the creation of this issue, and added to `tests/t_examples` as suggested. What remains is for example 6-3 to have the same (there is currently a `t_ex6_3` but should be moved to `t_examples` for parallelism).
