### ISSUE TITLE
Plot_fit legend is gross for fits with multiple terms

### ISSUE THREAD

**Issue by pgkirsch** [convexengineering/gpfit#54]
Example:
![sample_plot_fit](https://cloud.githubusercontent.com/assets/8702579/20032563/c4c63c54-a349-11e6-93c8-e9812febcecc.png)

**Comment by bqpd** [comment]
most simply, you could drop the parens and use `**` instead of `^`

then you could drop the third decimal place?

also maybe use `u1` instead of `u_1`?

**Comment by whoburg** [comment]
If we used GPkit objects more heavily throughout GPfit, we could just use GPkit's formatting (and `replace("**", "^")`.
