### ISSUE TITLE
Ability to pre-specify the power on an independent variable

### ISSUE THREAD

**Issue by pgkirsch** [convexengineering/gpfit#62]
This might sound like a strange request, and I haven't really thought about how feasible it is, but it would be nice if a user could specify the power on a certain independent variable based on a priori knowledge of the underlying relationships.

For example, if I am fitting a function, `z = f(x, y)` and I know that z should go with `x^0.5`, it would be nice to "fix" that part of the regression, so I end up with something like `z = 4.58*x^0.5*y^0.234`.

**Comment by bqpd** [comment]
Why not fit z/x^0.5=u?
