### ISSUE TITLE
`which coverage` is blank on Jenkins reynolds, causing test failure

### ISSUE THREAD

**Issue by bqpd** [convexengineering/gpfit#77]
https://acdl.mit.edu/csi/view/convexengineering/job/gpfit_Push/64/

@galbramc, this is an unexpected error to say the least...if coverage had gone missing I'd be expecting more tests to fail!

**Comment by galbramc** [comment]
Fixed. I had to add /home/jenkins/.local/bin/ to the PATH in the jenkins script.

**Comment by bqpd** [comment]
Noted, I'll try that next time. Thanks!
