### ISSUE TITLE
v0.1 refactor

### ISSUE THREAD

**Issue by pgkirsch** [convexengineering/gpfit#95]
I propose we create a 0.0 release of GPfit and then perform a pretty wholesale refactor of the code. Here is the list of changes I would like to make:

- [x] General code tightening (more concise code, less unnecessary whitespace)
- [x] Py3 only (e.g. delete `__future__` imports)
- [x] Delete legacy Matlab code
- [x] Better variable naming
    - [x] Appropriate use of case (rename upper case and mixed case vars unless global)
- [x] Better function naming
    - [x] Rename `get_params`
    - [x] Rename `ba_init`
- [x] Better class naming
    - [x] Rename `FitCS`
- [x] Code restructuring
    - [x] MA, SMA, ISMA should all be in one module
    - [x] Reduce confusing overlap of naming of `fit.py` and `fit_constraintset.py`
    - [x] Separate FitCS and XfoilFit (move to `xfoil.py`)
    - [x] Group `lse_scaled` and `lse_implicit` into one module
    - ~Fit should be a class not a function~
    - ~Eliminate `plot_fit.py` and `print_fit.py` (they should be class methods)~
- [x] Remove examples/tests redundancy
    - [x] Better naming of the examples too
- #98
- ~Write the Getting Started docs page~

There is a little overlap with #73 but would be good to include those items too!

@bqpd @whoburg any objections or things you want to add?

**Comment by bqpd** [comment]
Those look good to me! I might just add "write the Getting Started docs page"?

**Comment by pgkirsch** [comment]
Good call. The docs need a lot of love but that seems like an appropriate piece to include in this effort.

**Comment by bqpd** [comment]
The cleaner the API the shorter that page will be, too!

**Comment by whoburg** [comment]
@pgkirsch this sounds fantastic! What are your thoughts on using a code formatter like `black` to accomplish some of the earlier bullets?

**Comment by pgkirsch** [comment]
Thanks @whoburg! `black` seems cool, I'll give it a go.

**Comment by pgkirsch** [comment]
@whoburg I ran black on the code. It certainly brings nice uniformity and saves time spent mindlessly formatting code.

There are a few things I don't love though.
For instance, I'm not a fan of its policy on whitespace around `*`, `/`, `**` operators. I believe PEP allows `a = x*y + z**2` and I've always thought that looks nicer and more concise than `a = x * y + z ** 2`.

It also does makes some weird changes like:
```
-Vdd = random_sample(1000,) + 1
# ...
+Vdd = (
+    random_sample(
+        1000,
+    )
+    + 1
+)
```
Sure, that original line probably isn't great style and the black change can be fixed by assigning `x = random_sample` and doing `Vdd = x + 1` but it still feels odd to enforce a change that seems to make the code _less_ readable.

Lastly, rather than making the code more concise, it increased the total lines of code in the main directory very slightly from 906 to 941 (despite allowing lines up 88 chars long).

Anyway don't mean to complain too much, it's clearly a powerful tool and I'm on board with continuing to use it. I just wanted to flag a few minor things that gave me pause.

(cc @bqpd)

**Comment by bqpd** [comment]
Yeah the best use I've seen of black is to pretty-print long data entries for adding quick tests: just copy-paste in one line, then run black to line-break etc.

**Comment by bqpd** [comment]
(also it would've been super useful back when we were first linting everything!)

**Comment by whoburg** [comment]
Good discussion @pgkirsch and @bqpd, I'm all for whatever is most pleasing and efficient to use, whether that includes a code formatter or not. Completely up to you.

**Comment by whoburg** [comment]
Good discussion @pgkirsch and @bqpd, I'm all for whatever is most pleasing and efficient to use, whether that includes a code formatter or not. Completely up to you, no strong feelings here.

**Comment by pgkirsch** [comment]
Just coming back here to say that I've fully come around on black and would support using it not only in gpfit but also in gpkit, maybe once the great pylint refactor of 2024 is merged 👀
